# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v1.6.1
    hooks:
      - id: verify-copyright
        args: [--fix, --spdx]
        files: |
          (?x)
              [.](jq|py|sh|toml|yml|yaml)$|
              Dockerfile$
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.30.0
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: prevent-comitting-autogenerated-dockerfile-changes
        name: "prevent comitting autogenerated Dockerfile changes"
        entry: python ./ci/check-dockerfiles.py
        language: system
        pass_filenames: false
