# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
ci/sync-base-env.sh auto-generates ENV statements and writes them to ci-wheel.Dockerfile

This script is used to ensure they aren't accidentally comitted to source control.

Verify that no autogenerated content is committed in ci-wheel.Dockerfile.
"""

from pathlib import Path

BEGIN_MARKER = "# BEGIN base-image ENV (used by ci/sync-base-env.sh, do not edit)"
END_MARKER = "# END base-image ENV (used by ci/sync-base-env.sh, do not edit)"

DOCKERFILE = Path(__file__).resolve().parent.parent / "ci-wheel.Dockerfile"

lines = [line for line in DOCKERFILE.read_text().splitlines()]

begins = [i for i, line in enumerate(lines) if line == BEGIN_MARKER]
ends = [i for i, line in enumerate(lines) if line == END_MARKER]

if len(begins) != 1:
    raise ValueError(
        f"ERROR [ci-wheel.Dockerfile]: Expected exactly 1 line '{BEGIN_MARKER}', found {len(begins)}.",
    )
if len(ends) != 1:
    raise ValueError(
        f"ERROR [ci-wheel.Dockerfile]: Expected exactly 1 line '{END_MARKER}', found {len(ends)}.",
    )

begin_line = begins[0] + 1
end_line = ends[0] + 1
if end_line != begin_line + 1:
    raise ValueError(
        f"ERROR [ci-wheel.Dockerfile]: Expected line '{END_MARKER}' immediately after line '{BEGIN_MARKER}'"
        f" (found them at lines {begin_line} and {end_line})."
        " Remove any lines between them. That content is generated by ci/sync-base-env.sh"
        " at build time and should not be committed."
    )
