name: build and publish imgs workflow

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute matrix
        id: compute-matrix
        run: |
          MATRIX=$(ci/compute-matrix.sh)
          echo "MATRIX=${MATRIX}" | tee -a ${GITHUB_OUTPUT}
        env:
          BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
  docker:
    needs: compute-matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
      fail-fast: false
    secrets: inherit
    uses: ./.github/workflows/build-image.yaml
    with:
      ARCHES: ${{ toJSON(matrix.ARCHES) }}
      CUDA_VER: ${{ matrix.CUDA_VER }}
      LINUX_VER: ${{ matrix.LINUX_VER }}
      PYTHON_VER: ${{ matrix.PYTHON_VER }}
      IMAGE_REPO: ${{ matrix.IMAGE_REPO }}
      IMAGE_NAME: ${{ matrix.IMAGE_NAME }}
  build-multiarch-manifest:
    name: manifest (${{ matrix.CUDA_VER }}, ${{ matrix.PYTHON_VER }}, ${{ matrix.LINUX_VER }}, ${{ matrix.IMAGE_REPO }})
    needs: [docker, compute-matrix]
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Create multiarch manifest
        env:
          ARCHES: ${{ toJSON(matrix.ARCHES) }}
          CUDA_VER: ${{ matrix.CUDA_VER }}
          LINUX_VER: ${{ matrix.LINUX_VER }}
          PYTHON_VER: ${{ matrix.PYTHON_VER }}
          IMAGE_REPO: ${{ matrix.IMAGE_REPO }}
          BUILD_TYPE: ${{ inputs.build_type }}
          IMAGE_NAME: ${{ matrix.IMAGE_NAME }}
        run: ci/create-multiarch-manifest.sh
  delete-temp-images:
    needs: [compute-matrix, build-multiarch-manifest]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove temporary images
        run: ci/remove-temp-images.sh
        env:
          GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ matrix.IMAGE_NAME }}
          ARCHES: ${{ toJSON(matrix.ARCHES) }}
