# SPDX-FileCopyrightText: Copyright (c) 2023-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: ci

on:
  push:
    branches:
      - "pull-request/[0-9]+"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Please keep pr-builder as the top job here
  pr-builder:
    needs:
      - build-images
      - changed-files
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@main
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
    permissions:
      contents: read
      id-token: write
      pull-requests: read
  changed-files:
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@main
    with:
      files_yaml: |
        build_images:
          - '**'
          - '!.github/CODEOWNERS'
          - '!.github/copy-pr-bot.yaml'
          - '!.github/ops-bot.yaml'
          - '!.github/zizmor.yml'
          - '!.gitignore'
          - '!.pre-commit-config.yaml'
          - '!CONTRIBUTING.md'
          - '!LICENSE'
          - '!README.md'
          - '!SECURITY.md'
          - '!ci/release/update-version.sh'
          - '!renovate.json'
  build-images:
    uses: ./.github/workflows/build-and-publish-images.yaml
    needs: changed-files
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).build_images
    with:
      build_type: pull-request
    secrets:
      GPUCIBOT_DOCKERHUB_USER: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      GPUCIBOT_DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
