name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-images:
    uses: ./.github/workflows/build-and-publish-images.yml
    with:
      push: false
    secrets: inherit
